@startuml class-ddos-detection
hide circle
skinparam classAttributeIconSize 0

class DDoSUseCase {
    - _repository: ModelRepository
    - _publisher: PublisherPort
    - _result_repository: ResultRepositoryPort
    
    + __init__(repository: ModelRepository, publisher: PublisherPort, result_repository: ResultRepositoryPort)
    + execute(input_data: DDoSInput): None {async}
}

@enduml
