@startuml class-web-attack
hide circle
skinparam classAttributeIconSize 0

class WebAttackUseCase {
    - _repository: ModelRepository
    - _publisher: PublisherPort
    - _result_repository: ResultRepositoryPort
    
    + __init__(repository: ModelRepository, publisher: PublisherPort, result_repository: ResultRepositoryPort)
    + execute(input_data: WebAttackInput, window_start: datetime, window_end: datetime): None {async}
}

@enduml
