@startuml feature-reaction-escalation
top to bottom direction

skinparam packageStyle folder
skinparam linetype ortho
skinparam ranksep 120
skinparam nodesep 55
skinparam DefaultFontSize 27

hide circle
hide empty members

together {
  package "presentation" {
    class DetectionResultConsumer
    class ReactionDeadLetterConsumer
  }
}

together {
  package "service" {
    abstract class ReactionService
    interface AlertService
    interface ReactionLogService
    interface IpBlockService
    interface RateLimitService
    interface ScaleService
    interface ReactionEventPort
    interface AlertChannel
    interface WhitelistService
    interface DroppedReactionService

    ReactionService -[hidden]down- AlertService
    AlertService -[hidden]down- ReactionLogService
    ReactionLogService -[hidden]down- IpBlockService
    IpBlockService -[hidden]down- RateLimitService
    RateLimitService -[hidden]down- ScaleService
    ScaleService -[hidden]down- ReactionEventPort
    ReactionEventPort -[hidden]down- AlertChannel
    AlertChannel -[hidden]down- WhitelistService
    WhitelistService -[hidden]down- DroppedReactionService
  }
}

together {
  package "infrastructure.service.impl" {
    abstract class EscalatingIpReactionService
    class BruteForceReactionService
    class DDoSReactionService
    class TrafficReactionService
    class WebAttackReactionService
    class CompositeAlertService
    class DiscordAlertService
    class ResendAlertService
    class SmtpAlertService
    class RedisIpBlockService
    class RedisRateLimitService
    class RedisScaleService
    class JpaReactionLogService
    class JpaDroppedReactionService
    class SimulationWhitelistClient

    EscalatingIpReactionService -[hidden]down- BruteForceReactionService
    BruteForceReactionService -[hidden]down- DDoSReactionService
    DDoSReactionService -[hidden]down- TrafficReactionService
    TrafficReactionService -[hidden]down- WebAttackReactionService

    CompositeAlertService -[hidden]down- DiscordAlertService
    DiscordAlertService -[hidden]down- ResendAlertService
    ResendAlertService -[hidden]down- SmtpAlertService

    RedisIpBlockService -[hidden]down- RedisRateLimitService
    RedisRateLimitService -[hidden]down- RedisScaleService

    JpaReactionLogService -[hidden]down- JpaDroppedReactionService
    JpaDroppedReactionService -[hidden]down- SimulationWhitelistClient

    EscalatingIpReactionService -[hidden]right- CompositeAlertService
    CompositeAlertService -[hidden]right- RedisIpBlockService
    RedisIpBlockService -[hidden]right- JpaReactionLogService
  }
}

together {
  package "infrastructure.mq" {
    class ReactionResultPublisher
  }

  package "infrastructure.persistence" {
    interface ReactionLogRepository
    class ReactionLogEntity
    interface DroppedReactionRepository
    class DroppedReactionEntity

    ReactionLogRepository -[hidden]down- ReactionLogEntity
    ReactionLogEntity -[hidden]down- DroppedReactionRepository
    DroppedReactionRepository -[hidden]down- DroppedReactionEntity
  }
}

"presentation" -[hidden]down- "service"
"service" -[hidden]down- "infrastructure.service.impl"
"infrastructure.service.impl" -[hidden]down- "infrastructure.mq"
"infrastructure.mq" -[hidden]right- "infrastructure.persistence"

DetectionResultConsumer o-- ReactionService
ReactionDeadLetterConsumer o-- DroppedReactionService

ReactionService o-- AlertService
ReactionService o-- ReactionLogService

EscalatingIpReactionService --|> ReactionService
EscalatingIpReactionService o-- IpBlockService
EscalatingIpReactionService o-- RateLimitService
EscalatingIpReactionService o-- WhitelistService

BruteForceReactionService --|> EscalatingIpReactionService
DDoSReactionService --|> EscalatingIpReactionService

TrafficReactionService --|> ReactionService
TrafficReactionService o-- ScaleService

WebAttackReactionService --|> ReactionService
WebAttackReactionService o-- IpBlockService
WebAttackReactionService o-- WhitelistService

CompositeAlertService ..|> AlertService
CompositeAlertService o-- AlertChannel

DiscordAlertService ..|> AlertChannel
ResendAlertService ..|> AlertChannel
SmtpAlertService ..|> AlertChannel

RedisIpBlockService ..|> IpBlockService
RedisIpBlockService ..> EscalatingIpReactionService
RedisRateLimitService ..|> RateLimitService
RedisScaleService ..|> ScaleService

SimulationWhitelistClient ..|> WhitelistService

JpaReactionLogService ..|> ReactionLogService
JpaReactionLogService o-- ReactionEventPort
JpaReactionLogService o-- ReactionLogRepository

ReactionResultPublisher ..|> ReactionEventPort
ReactionLogRepository o-- ReactionLogEntity

JpaDroppedReactionService ..|> DroppedReactionService
JpaDroppedReactionService o-- DroppedReactionRepository
DroppedReactionRepository o-- DroppedReactionEntity

@enduml
