@startuml sequence-log-processing
autonumber
skinparam BoxPadding 10
skinparam ParticipantPadding 10

box "Application"
participant "LogProcessingWorker" as Worker
end box

box "Domain Service (LogProcessingService)"
participant "LogProcessingService" as Service
end box

Worker -> Service : process(RawLog)
alt rawLog.source == HTTP
    Service -> Service : parseHttp(RawLog)
else rawLog.source == FLOW
    Service -> Service : parseFlow(RawLog)
end
Service --> Worker : ProcessingResult (Http or Flow)

@enduml
