@startuml sequence-log-processing
autonumber
<style>
root {
  BackgroundColor white
  LineColor black
  FontColor black
}
sequenceDiagram {
  participant {
    Padding 10
  }
}
</style>

participant "LogProcessingWorker" as Worker
participant "LogProcessingService" as Service

Worker -> Service : process(RawLog)
alt rawLog.source == HTTP
    Service -> Service : parseHttp(RawLog)
else rawLog.source == FLOW
    Service -> Service : parseFlow(RawLog)
end
Service --> Worker : ProcessingResult (Http or Flow)

@enduml
