spring:
  application:
    name: log-analyzer

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres-log-analyzer:5432/log-analyzer
    username: sa
    password: "1234"
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis-log-analyzer
      port: 6379
      password: ultra_secure_123

  rabbitmq:
    host: rabbitmq-log-analyzer
    port: 5672
    username: sa
    password: "1234"
    virtual-host: /