@startuml component-based
top to bottom direction

skinparam shadowing false
skinparam packageStyle folder
skinparam linetype ortho
skinparam defaultFontName "Sans"
skinparam ArrowColor #555555
skinparam packageBorderColor #333333
skinparam padding 5
skinparam ranksep 120
skinparam nodesep 50
skinparam DefaultFontSize 16
skinparam packageFontSize 12

hide circle
hide empty members

package pages {
  class " " as _pagesA
  class " " as _pagesB
  hide _pagesA
  hide _pagesB
  _pagesA -[hidden]right- _pagesB
}

package components {
  class " " as _componentsA
  class " " as _componentsB
  hide _componentsA
  hide _componentsB
  _componentsA -[hidden]right- _componentsB
}

package hooks {
  class " " as _hooksA
  class " " as _hooksB
  hide _hooksA
  hide _hooksB
  _hooksA -[hidden]right- _hooksB
}

package "api.js" as api {
  class " " as _apiA
  class " " as _apiB
  hide _apiA
  hide _apiB
  _apiA -[hidden]right- _apiB
}

' =====================================================
' Layout
' =====================================================

pages -[hidden]down- components
components -[hidden]down- hooks
hooks -[hidden]right- api

' =====================================================
' Dependencies
' =====================================================

pages ..> components
components ..> hooks

pages ..> api
hooks ..> api

@enduml