@startuml layered
top to bottom direction

skinparam shadowing false
skinparam packageStyle folder
skinparam linetype ortho
skinparam defaultFontName "Sans"
skinparam ArrowColor #555555
skinparam packageBorderColor #333333
skinparam padding 5
skinparam ranksep 120
skinparam nodesep 50
skinparam DefaultFontSize 16
skinparam packageFontSize 12

hide circle
hide empty members

package presentation {
  class " " as _presentationA
  class " " as _presentationB
  hide _presentationA
  hide _presentationB
  _presentationA -[hidden]right- _presentationB
}

package service {
  package "service.dto" {
    package "service.dto.alert" {
      class " " as _service_dto_alertA
      class " " as _service_dto_alertB
      hide _service_dto_alertA
      hide _service_dto_alertB
      _service_dto_alertA -[hidden]right- _service_dto_alertB
    }
  }
}

package infrastructure {
  package "infrastructure.config" {
    class " " as _infrastructure_configA
    class " " as _infrastructure_configB
    hide _infrastructure_configA
    hide _infrastructure_configB
    _infrastructure_configA -[hidden]right- _infrastructure_configB
  }

  package "infrastructure.mq" {
    class " " as _infrastructure_mqA
    class " " as _infrastructure_mqB
    hide _infrastructure_mqA
    hide _infrastructure_mqB
    _infrastructure_mqA -[hidden]right- _infrastructure_mqB
  }

  package "infrastructure.persistence" {
    package "infrastructure.persistence.entity" {
      class " " as _infrastructure_persistence_entityA
      class " " as _infrastructure_persistence_entityB
      hide _infrastructure_persistence_entityA
      hide _infrastructure_persistence_entityB
      _infrastructure_persistence_entityA -[hidden]right- _infrastructure_persistence_entityB
    }
    package "infrastructure.persistence.repository" {
      class " " as _infrastructure_persistence_repositoryA
      class " " as _infrastructure_persistence_repositoryB
      hide _infrastructure_persistence_repositoryA
      hide _infrastructure_persistence_repositoryB
      _infrastructure_persistence_repositoryA -[hidden]right- _infrastructure_persistence_repositoryB
    }

    "infrastructure.persistence.entity" -[hidden]right- "infrastructure.persistence.repository"
  }

  package "infrastructure.service" {
    package "infrastructure.service.impl" {
      class " " as _infrastructure_service_implA
      class " " as _infrastructure_service_implB
      hide _infrastructure_service_implA
      hide _infrastructure_service_implB
      _infrastructure_service_implA -[hidden]right- _infrastructure_service_implB
    }
  }

  "infrastructure.config" -[hidden]right- "infrastructure.mq"
  "infrastructure.mq" -[hidden]down- "infrastructure.persistence"
  "infrastructure.persistence" -[hidden]right- "infrastructure.service"
}

presentation ..> service

infrastructure ..> service

presentation -[hidden]down- service
service -[hidden]down- infrastructure

@enduml
